canonical/opensearch-snap

- .github/workflows/snap.yaml
- CONTRIBUTOR.md
- scripts/wrappers/security-init.sh
- scripts/wrappers/setup.sh
- scripts/wrappers/start.sh
- snap/snapcraft.yaml
This PR contains:
- A github workflow with tests and publish to the snapcraft store
- A separate app for initializing the security index, allowing users to optionally / consciously run this app if needed
- Fix of some permissions and access 
- Removal of s3 reference and usage of Opensearch's own distributed tarballs (while security provides us with ours) 
- Bumped version of Opensearch to `2.2.1`
- Readme update
> Github workflow + refactoring of security index initialisation  

- .github/workflows/snap.yaml
- scripts/wrappers/start.sh
- scripts/wrappers/sys/set-sys-config.sh
This is a very small PR, that makes the interface `process-control` optional.
> Make process-control optional

- .github/workflows/on_push.yaml
- .github/workflows/release.yaml
This PR is about removing the old `edge` branch from the ci / cd workflow.
> Removed the edge branch from the workflow

- .github/workflows/release.yaml
This is a very minor PR to attempt a fix on a job not being called on the release pipeline.
> Renamed job name on release pipeline

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- CONTRIBUTOR.md
- README.md
- snap/snapcraft.yaml
This PR contains:
- upgrade of linux packages on the github actions (we got a security alert regarding outdated packages)
- bump of OpenSearch version to `2.4.1`
> Added linux packages upgrade on CI and bumped OpenSearch version

- .github/workflows/ci.yaml
- snap/snapcraft.yaml
This PR does the following:
- Bumped OpenSearch version to `2.5.0`
- Removed opensearch archive after extracting it
- Limited the dependency upgrades to the security ones
> Bumped version of opensearch to 2.5.0 + removed archive after extracting

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- README.md
- snap/snapcraft.yaml
This PR:
- bumps the version of opensearch to 2.6.0
- fixed error in readme
> Bumped version of opensearch to 2.6.0

- scripts/wrappers/sys/set-sys-config.sh
This PR:
- adds a test to handle when the `ulimit` is set to `unlimited`.
- commented out `ulimit -l unlimited` for now, until I confirm it's really needed.
> Added test on ulimit unlimited

- snap/snapcraft.yaml
This PR adds a restart logic to the opensearch service, always restarts with a waiting time of 20sec.
> Added restart rules for the opensearch service

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
This PR changes the release channel of the snap from previously `latest/edge` to now `2/edge`
> Changed release channel format

- .github/workflows/ci.yaml
- CONTRIBUTOR.md
- scripts/helpers/io.sh
- setup-dev-env.sh
- snap/hooks/install
- snap/snapcraft.yaml
This PR implements [DPE-2121](https://warthogs.atlassian.net/browse/DPE-2121), namely this PR: 
- adds support for the [Performance analyzer](https://opensearch.org/docs/latest/monitoring-your-cluster/pa/index/#storage), namely this PR adds a `read / write` plug for the path `/dev/shm/performanceanalyzer`
[DPE-2121]: https://warthogs.atlassian.net/browse/DPE-2121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DPE-2121] Added support for performance analyzer

- .github/workflows/ci.yaml
- snap/hooks/install
According to 
- https://opensearch.org/blog/plugins-intro/ => Loading plugins
together with our experience, plugins installed in `$OPENSEARCH_HOME/plugins` are automatically loaded at startup.
Once we benefit from this feature, config should also get moved to the level of the snap.
> [DPE-3108] Prometheus configuration at startup

- .github/workflows/ci.yaml
- snap/snapcraft.yaml
Still confirming with COS Team, but (based on existing DP charms' experience) it seems that need to allow [this](https://github.com/canonical/grafana-agent-snap/blob/main/snap/snapcraft.yaml#L19) to connect, so that logs could be shipped to COS. 
[Confirmation](https://matrix.to/#/!nHXpRkcSNJHlHdUGbQ:ubuntu.com/$eIG48CiRYmuuYzDg16c5AXDIVEwcH6xwzegiZdEkJac?via=ubuntu.com&via=matrix.org) from COS Team that the slot-plug connection is needed for strictly confined snaps.
> [DPE-2938] Logs plug to snap

- .github/workflows/ci.yaml
- snap/snapcraft.yaml
Add default repository-s3 plugin. The plugin must be downloaded and installed in the correct folder.
This PR also reorganizes the CI tests, as backup plugin was originally used in the upgrade testing.
> Backup: repository-s3 plugin should be already installed

- .github/workflows/ci.yaml
- snap/snapcraft.yaml
This PR adds the `repository-gcs` plugin.
The plugin is downloaded from the artifacts.opensearch.org.
> [DPE-3309] Add support for repository-gcs

- snap/snapcraft.yaml
Extend the snap to download  the newer version of v2.10, containing core-plugins s3 and gcs.
> [DPE-3461] Add build from source v2.10.0-ubuntu1

- .github/workflows/release.yaml
- README.md
This repo's status is not displayed in the [Charm Engineering Releases](https://releases.juju.is/?team=Data) overview.
Added workflow badges for 
* Publish to snap store
* Tests
and renamed workflow in `release.yaml` to "Publish to Snap Store".
> Added badges to README.md

- snap/snapcraft.yaml
Update the OpenSearch binaries to use our built from source 2.11.1 version.
> [DPE-3647] Update to 2.11.1-ubuntu0 binaries

- .github/workflows/ci.yaml
- snap/snapcraft.yaml
Updates the OpenSearch to 2.12.0 built from source. Updates JDK to v21 and fixes CI.
> [DPE-3647] Update to 2.12.0

- snap/snapcraft.yaml
Update snap to 2.14.0. There are neither new plugins nor any major change from snap's perspective from 2.13.0
> [DPE-4305] Update snaps to 2.14.0

- snap/hooks/install
- snap/snapcraft.yaml
Add support for home directory for snap_daemon both by setting `$HOME` and JVM's `-Duser.home`.
Closes #67
> [DPE-4732] Add support for homedir

- snap/snapcraft.yaml
This PR backports upstream fix for ML Commons: https://github.com/opensearch-project/ml-commons/pull/2675
To be added to our distribution.
Given we are currently targeting upstream branch 2.14, instead of upstream tag 2.14.0.0, this build is using a new release from our build from source: 2.14.0-ubuntu1.
> [DPE-5047] Update snap to 2.14.0-ubuntu1 with ML Commons fix

- snap/snapcraft.yaml
Updates the snap to 2.16.0 version.
It also carries the `security` backport:
* https://github.com/opensearch-project/security/pull/4640
> [DPE-5359][DPE-5360] Update to 2.16.0
